server:
  port: 8090
  context-path: /sac

spring:
  profiles:
    active: dev
  application:
    name: paascloud-service-auth
  datasource:
    url: jdbc:mysql://paascloud-db-mysql:3306?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456